{ config, pkgs, lib, ... }:

let
  # Based on:
  # https://github.com/nix-community/home-manager/issues/1658
  hmListFilesScript =
    let
      files = builtins.concatStringsSep "\n" (
        map (file: file.target) (
          builtins.filter
            (file: !file.recursive)
            (lib.mapAttrsToList (_: file: file) config.home.file)
        )
      );
    in
    pkgs.writeShellScriptBin "my-hm-dotfiles" ''
      # List all dotfiles generated by Home Manager
      cat <<EOF
      ${files}
      EOF
    '';

  macSpoofScript = pkgs.writeShellScriptBin "mac-spoof" ''
    sudo ip link set enp0s13f0u2u1 down
    sudo ip link set enp0s13f0u2u1 address 3c:97:0e:51:74:89
    sudo ip link set enp0s13f0u2u1 up
  '';
in
{
  home.packages = [ 
    hmListFilesScript
    macSpoofScript
  ];
}
